# Generated by Django 3.1.2 on 2020-10-10 10:17

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_fellow', models.BooleanField(default=False)),
                ('is_associate', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFellow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('company_profile', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=10, verbose_name='Phone number (without +91 or 0): 88xxx xxx88')),
                ('image', models.ImageField(default='default_fellow.png', upload_to='profile_pics_fellow')),
                ('is_fellow', models.BooleanField(default=True)),
                ('fellow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAssociate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('gender', models.CharField(default='Male/Female', max_length=6)),
                ('phone', models.CharField(default='', max_length=10, verbose_name='Phone number (without +91 or 0): 88xxx xxx88')),
                ('aadhaar', models.PositiveIntegerField(default='0', validators=[django.core.validators.MaxValueValidator(9999999999999999)], verbose_name='UIDAI (Aadhaar) number: (will be used for verification purpose)')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Date of birth: (yyyy/mm/dd)')),
                ('image', models.ImageField(default='default_associate.png', upload_to='profile_pics_associate')),
                ('max_qualification', models.CharField(default='', max_length=25)),
                ('ssc_score', models.FloatField(default='100', verbose_name='10th score (%):')),
                ('ssc_result', models.FileField(default='', upload_to='associate_documents')),
                ('associate_bio', models.TextField(default='', max_length=300, verbose_name='About you')),
                ('work_ex', models.TextField(default='Enter your work experience if any', max_length=300)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2020, 10, 10, 15, 47, 52, 585059))),
                ('punctuality_score', models.PositiveIntegerField(default='0')),
                ('associate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_hired', models.BooleanField(default=False)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='blog.post')),
            ],
            options={
                'unique_together': {('associate', 'post')},
            },
        ),
    ]
