# Generated by Django 3.1.2 on 2020-10-21 14:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201010_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='associate_is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='associate_rating',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='application',
            name='fellow_is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='fellow_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 23, 57, 100582)),
        ),
    ]
