# Generated by Django 3.1.2 on 2020-10-21 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201021_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 25, 58, 930822)),
        ),
    ]
