# Generated by Django 3.1.2 on 2021-12-11 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211211_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileassociate',
            name='max_qualification',
        ),
        migrations.AddField(
            model_name='profileassociate',
            name='qualification',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('Under raduation', 'Under raduation'), ('Graduation', 'Graduation'), ('Other', 'Other')], default='Select', max_length=25, verbose_name='Qualification?'),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 17, 17, 1, 96446)),
        ),
    ]
