# Generated by Django 3.1.2 on 2021-12-11 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211211_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 17, 18, 53, 398476)),
        ),
    ]
