# Generated by Django 3.1.2 on 2020-10-22 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201022_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='associate_comment',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='fellow_comment',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 2, 15, 53, 838577)),
        ),
    ]
