# Generated by Django 3.1.2 on 2020-10-31 12:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201023_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefellow',
            name='estd',
            field=models.PositiveIntegerField(default='1998', validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Establishment year'),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='aadhaar',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MaxValueValidator(9999999999999999)], verbose_name='UIDAI (Aadhaar) number: (will be used for verification purpose)'),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 18, 24, 1, 457196)),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='phone',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Phone number (without +91 or 0): 88xxx xxx88'),
        ),
    ]
