# Generated by Django 3.1.2 on 2020-10-31 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201031_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='sent_to_emplorer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileassociate',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 22, 48, 20, 478002)),
        ),
    ]
