# Generated by Django 3.1.2 on 2020-10-31 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201031_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 23, 30, 28, 787024)),
        ),
    ]
