# Generated by Django 3.1.2 on 2020-12-19 13:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201219_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileassociate',
            name='punctuality_score',
        ),
        migrations.AddField(
            model_name='profileassociate',
            name='associate_avg_rating',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='profilefellow',
            name='fellow_avg_rating',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 18, 55, 29, 712360)),
        ),
    ]
