# Generated by Django 3.1.2 on 2020-12-27 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201219_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 23, 11, 6, 603900)),
        ),
        migrations.AlterField(
            model_name='profilefellow',
            name='fellow_avg_rating',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=2),
        ),
    ]
