# Generated by Django 3.1.2 on 2021-01-15 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201227_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='fellow_complained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='fellows_complaint',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='fellows_complaint_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='fellows_complaint_subject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='associate_avg_rating',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=2),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 4, 49, 58, 650446)),
        ),
    ]
