# Generated by Django 3.1.2 on 2021-01-15 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210116_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='associate_complained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='associates_complaint',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='associates_complaint_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='associates_complaint_subject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 5, 23, 14, 452048)),
        ),
    ]
