# Generated by Django 3.1.2 on 2021-01-27 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210116_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileassociate',
            name='hsc_result',
            field=models.FileField(blank=True, default='', upload_to='associate_documents'),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 18, 14, 58, 293590)),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='ssc_score',
            field=models.FloatField(default='100', verbose_name='12th score (%):'),
        ),
    ]
