# Generated by Django 3.1.2 on 2021-01-27 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210127_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='hsc_result',
            field=models.FileField(blank=True, default='Not Available', upload_to='associate_documents'),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 19, 7, 6, 474407)),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='work_ex',
            field=models.TextField(default='Fresher', max_length=300, verbose_name='Work Experience:'),
        ),
    ]
