# Generated by Django 3.1.2 on 2021-01-27 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210127_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileassociate',
            name='hsc_score',
            field=models.FloatField(default='100', verbose_name='12th score (%):'),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 19, 9, 25, 507001)),
        ),
    ]
