# Generated by Django 3.1.2 on 2021-01-27 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210127_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 19, 13, 46, 540077)),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='ssc_score',
            field=models.FloatField(default='100', verbose_name='10th score (%):'),
        ),
    ]
