# Generated by Django 3.1.2 on 2021-01-29 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210130_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 4, 39, 11, 591689)),
        ),
    ]
