# Generated by Django 3.1.2 on 2021-02-01 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210130_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='recall',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 23, 38, 19, 324078)),
        ),
    ]
