# Generated by Django 3.1.2 on 2021-02-04 14:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20210204_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 20, 19, 6, 193661)),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='phone',
            field=models.PositiveIntegerField(default='9', unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Phone number (without +91 or 0): 88xxx xxx88'),
        ),
        migrations.AlterField(
            model_name='profilefellow',
            name='phone',
            field=models.CharField(default='9', max_length=10, unique=True, verbose_name='Phone number (without +91 or 0): 88xxx xxx88'),
        ),
    ]
