# Generated by Django 3.1.2 on 2021-02-04 14:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20210204_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='aadhaar',
            field=models.PositiveIntegerField(default='9', validators=[django.core.validators.MaxValueValidator(9999999999999999)], verbose_name='UIDAI (Aadhaar) number: (will be used for verification purpose)'),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 20, 21, 29, 816874)),
        ),
    ]
