# Generated by Django 3.1.2 on 2021-02-04 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20210204_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 22, 41, 50, 627370)),
        ),
    ]
