# Generated by Django 3.1.2 on 2021-02-18 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20210204_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='note_by_partshala',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profileassociate',
            name='note_by_partshala',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profilefellow',
            name='note_by_partshala',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 22, 21, 26, 815764)),
        ),
    ]
