# Generated by Django 3.1.2 on 2021-02-18 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20210218_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefellow',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 22, 51, 18, 745072)),
        ),
    ]
