# Generated by Django 3.1.2 on 2021-02-20 08:06

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20210220_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 13, 36, 25, 173460)),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone number: +9188xxx xxx88'),
        ),
        migrations.AlterField(
            model_name='profilefellow',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone number: +9188xxx xxx88'),
        ),
    ]
