# Generated by Django 3.1.2 on 2021-02-24 19:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20210220_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileassociate',
            name='dl_copy',
            field=models.FileField(blank=True, default='Not Applicable', upload_to='associate_documents'),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='aadhaar',
            field=models.PositiveIntegerField(default='9', validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='UIDAI (Aadhaar) number: (will be used for verification purpose)'),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='hsc_result',
            field=models.FileField(blank=True, default='Not Applicable', upload_to='associate_documents'),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 0, 36, 18, 74071)),
        ),
        migrations.AlterField(
            model_name='profilefellow',
            name='estd',
            field=models.PositiveIntegerField(default='1998', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Establishment year'),
        ),
    ]
