# Generated by Django 3.1.2 on 2021-08-06 09:39

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20210225_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='8888888888', max_length=128, region=None, verbose_name='Phone number: +9188xxx xxx88'),
        ),
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 15, 9, 3, 767147)),
        ),
    ]
