# Generated by Django 3.1.2 on 2021-08-06 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20210806_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 15, 22, 38, 343541)),
        ),
    ]
