# Generated by Django 3.1.2 on 2021-08-06 10:16

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20210806_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 15, 46, 35, 82405)),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='8888888888', max_length=128, region=None, unique=True, verbose_name='Phone number: +9188xxx xxx88'),
        ),
    ]
