# Generated by Django 3.1.2 on 2020-10-10 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('skills_reqd', models.TextField(default='Skills expected')),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start date: (yyyy-mm-dd)')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='End date: (yyyy-mm-dd)')),
                ('start_time', models.TimeField(null=True, verbose_name='Start time: (HH:MM)')),
                ('end_time', models.TimeField(null=True, verbose_name='End time: (HH:MM)')),
                ('city', models.CharField(default='', max_length=15)),
                ('vacancy', models.IntegerField(default='1')),
                ('address', models.TextField(default='Reporting Address')),
                ('stipend', models.IntegerField(blank=True, default=0)),
                ('filled', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
