# Generated by Django 3.1.2 on 2020-10-21 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_fellow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vacancy',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
