# Generated by Django 3.1.2 on 2020-12-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contactus_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
