# Generated by Django 3.1.2 on 2020-12-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rejection_note',
            field=models.TextField(default='Resubmit'),
        ),
    ]
