# Generated by Django 3.1.2 on 2021-02-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_no_of_hirings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='note_by_partshala',
            field=models.TextField(default=''),
        ),
    ]
