# Generated by Django 3.1.2 on 2021-02-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_note_by_partshala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rejection_note',
        ),
    ]
