# Generated by Django 3.1.2 on 2021-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_rejection_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rejection_note',
            field=models.TextField(default='Resubmit'),
        ),
    ]
